config/routes.rb
Rails.application.routes.draw do

  match "profile" => "users#show", :via => [:get], :as => 'user_show'

  resources :servers do
    resources :packages
  end

  devise_for :users

  root :to => "welcome#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :recoverable,
         :rememberable, :registerable, :trackable
end

app/models/package.rb
class Package < ActiveRecord::Base
  
  SUPPORTED_PACKAGETYPES = ["rpm", "deb", "gem"]
  validates_each :pkgtype do |record, attr, value|
    record.errors.add attr, 'isn\'t in' + SUPPORTED_PACKAGETYPES.to_s unless SUPPORTED_PACKAGETYPES.include?(value.downcase)
  end    
  belongs_to :server
  
  validates :name, :pkgversion, :architecture, :presence => true  

  def long_name
    [:name, :pkgversion, :architecture].join()
  end
end

app/models/server.rb
class Server < ActiveRecord::Base
  has_many :packages, :dependent => :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable,
         :rememberable, :registerable, :trackable

  has_many :servers, :dependent => :destroy
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :authenticate_admin!

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => :token

  def index
  end

  def token
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_server

  # GET /servers/2/packages
  def index
    @server = Server.find(params[:server_id])
    @packages = @server.packages
  end

  # GET /servers/2/packages/3
  def show
    @server = Server.find(params[:server_id])
    @package = @server.packages.find(params[:id])
  end

  # GET /servers/2/packages/new
  def new
    @server = Server.find(params[:server_id])
    @package = @server.packages.build
  end

  # GET /servers/2/packages/3/edit
  def edit
    @server = Server.find(params[:server_id])
    @package = Package.find(params[:id])
  end

  # POST /servers/2/packages
  def create
    @package = Package.new(package_params)
    @package.server = Server.find(params[:server_id])

    if @package.save
      flash[:notice] = 'Package was successfully created.'
      redirect_to server_url(@package.server)
    else
      render :action => "new" 
    end
  end

  # PUT /servers/1/packages/2
  def update
    @package = Package.find(params[:id])
    @server = Server.find(params[:server_id])
    if @package.update_attributes(package_params)
      flash[:notice] = 'Package was successfully updated.'
      redirect_to server_url(@server)
    else
      render :action => "edit" 
    end
  end

  # DELETE /server/1/packages/2
  def destroy
    @package = Package.find(params[:id])
    @package.destroy

    respond_to do |format|
      format.html { redirect_to(server_packages_url) }
      format.xml  { head :ok }
    end
  end

  protected
  
  def find_server
    if params[:server_id]
      @server = Server.find(params[:server_id])
      @user = @server.user
    else
      @package = Package.find(params[:id])
      @user = @package.server.user
    end
    unless current_user == @user
      redirect_to @user, :alert => 'Permission error!'
    end
  end

  private

  def package_params
    params.require(:package).permit(:pkgtype, :name, :architecture, :pkgversion)
  end

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_user

  # GET /servers
  def index
    @servers = @user.servers
  end

  # GET /servers/2
  def show
    @server = Server.find(params[:id])
  end

  # GET /servers/new
  def new
    @server = @user.servers.build
  end

  # GET /servers/2/edit
  def edit
    @server = @user.servers.find(params[:id])
  end

  # POST /servers
  def create
    @server = @user.servers.new(server_params)
    if @server.save
      flash[:notice] = "Server was successfully created"
      redirect_to server_url(@server)
    else
      render :action => "new"
    end
  end

  # PUT /users/1/servers/2
  def update
    @server = @user.servers.find(params[:id])

    if @server.update_attributes(server_params)
      flash[:notice] = "Server was successfully updated"
      redirect_to server_url(@server)
    else
      render :action => "edit" 
    end
  end

  # DELETE /servers/1
  def destroy
    @server = @user.servers.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to(servers_url) }
      format.xml  { head :ok }
    end
  end

  protected

  def find_user
    if params[:user_id]
      @user = User.find(params[:user_id])
    else
      @server = Server.find(params[:id])
      @user = @server.user
    end
    unless current_user == @user
      redirect_to @user, :alert => "Permission error!"
    end
  end

  private

  def server_params
    params.require(:server).permit(:name, :ip)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!, :only => :token
  
  def index
  end

  def token
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Migrationator</title>
  <%= stylesheet_link_tag :migrationator %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<!-- logged in as @user.name-->
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing servers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Ip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @servers.each do |server| %>
  <tr>
    <td><%= server.name %></td>
    <td><%= server.ip %></td>
    <td><%= link_to 'Show', server %></td>
    <td><%= link_to 'Edit', edit_server_path(server) %></td>
    <td><%= link_to 'Destroy', server, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p>
  <b>Name:</b>
  <%= @server.name %>
</p>

<p>
  <b>Ip:</b>
  <%= @server.ip %>
</p>


<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>

app/views/welcome/index.html.erb
<div class="welcome-top">
    <div class="main-header">Migrationator</div>
    <div class="login-box" style="float:right;clear:none;">
        <input type="text" />
    </div>        
</div>

<div class="content" style="margin:0 auto;text-align:center">
    Migrationator  
</div>



<% unless user_signed_in? -%>
  <p> <%= link_to 'Sign up', new_user_registration_path %></p>
  <p> <%= link_to 'Sign in', new_user_session_path %></p> 
<% end -%>